### ISSUE TITLE
Valorant ''Version mismatch''

### ISSUE THREAD

**Issue by Speeten** [molenzwiebel/Deceive#101] opened 2021-06-05 14:44 UTC
Is the deceive plugin not up to date or have i done something wrong?
![image](https://user-images.githubusercontent.com/85403522/120895420-2c07ec00-c61d-11eb-9770-f5728ea1c247.png)

Be great for anyone to tell me! :)
This is for Valorant btw. 05.06.2021

**Comment by aPinat** [comment] 2021-06-05 15:08
dupe of #78 #73 #95, please do search older issues first

**Closed** 2021-06-05 19:30 UTC
