### ISSUE TITLE
Deceive is not working 

### ISSUE THREAD

**Issue by RingoRAG** [molenzwiebel/Deceive#166] opened 2022-11-08 09:50 UTC
![Unbenannt](https://user-images.githubusercontent.com/117725217/200532337-5ca9d8b1-f904-403d-8d1b-be906a5cad66.PNG)

**Comment by molenzwiebel** [comment] 2022-11-10 15:11
Duplicate of #164.

**Closed by molenzwiebel** 2022-11-10 15:11 UTC
