### ISSUE TITLE
1.5.1 breaks champion select chat, and possibly other chat aswell.

### ISSUE THREAD

**Issue by jayansonwong** [molenzwiebel/Deceive#25] opened 2019-11-24 14:22 UTC
Can't see or type anything into chat

**Comment by aPinat** [comment] 2019-11-24 15:56
![image](https://user-images.githubusercontent.com/17106472/69497267-40711180-0edb-11ea-910c-36e52ff7bcb9.png)
Works fine for me.

**Comment by jayansonwong** [comment] 2019-11-24 20:57
Yeah as soon as I use Deceive.exe chat just refuses to work. Is fine otherwise. Usually when I first enter champion select it says Connecting... and then disappears. After that its just an empty chat box. Can't interact with others at all.
![deceivenotworking](https://user-images.githubusercontent.com/32843708/69501427-c0f43a00-0efc-11ea-8f9e-8e34a751a7d6.jpg)

**Comment by DjordjeMandic** [comment] 2019-11-25 00:35
![image](https://user-images.githubusercontent.com/6750655/69504519-d16bdb00-0f23-11ea-9493-b7b585b9dbe9.png)

It just enters a loop

**Comment by aPinat** [comment] 2019-11-25 09:18
Ok, I think I know what causes @DjordjeMandic loop even though I can't reproduce it on my client...
Can you try this version and see if it fixes it for you?
https://github.com/aPinat/Deceive/releases/latest

@jayansonwong But your friends list/chat bar on the right, outside of lobby also works fine with Deceive? If it's only in Champ Select, does your bottom right chat window still work then? You can also try that version above and see whether it changes anything...

**Comment by jayansonwong** [comment] 2019-11-25 16:28
Hey, thanks for the quick replies. 
The new release fixes my issue :)

**Comment by aPinat** [comment] 2019-11-30 21:04
Fixed in #27. Can be closed.

**Closed** 2019-12-15 15:31 UTC
