### ISSUE TITLE
Valorant "Version Mismatch!"

### ISSUE THREAD

**Issue by ABongoCat** [molenzwiebel/Deceive#112] opened 2021-10-05 17:58 UTC
Just tried Deceive for LoL and was amazed. It did work for Valorant, except it shows this message. 
![image](https://user-images.githubusercontent.com/45139479/136077326-487c423a-4207-4ccd-98c9-d6dbfd81ebbd.png)

My Client is on this Version.
![image](https://user-images.githubusercontent.com/45139479/136076771-a200390f-bf3b-4f2e-8753-623197125814.png)

**Comment by aPinat** [comment] 2021-10-05 23:11
dupe of #78 #73 #95 #101, please do search older issues first

**Closed** 2022-04-06 12:46 UTC
