### ISSUE TITLE
Decieve not working with patch 9.24

### ISSUE THREAD

**Issue by RynLee** [molenzwiebel/Deceive#31] opened 2019-12-13 06:49 UTC
Stopped working after updating to new patch, 9.24

**Comment by aPinat** [comment] 2019-12-13 08:25
What region are you on and what exactly doesn't work as it works just fine for me?

**Comment by molenzwiebel** [comment] 2019-12-15 15:30
Closing this until further information, since I can not currently reproduce this.

**Closed by molenzwiebel** 2019-12-15 15:30 UTC
