### ISSUE TITLE
Decieve not working 

### ISSUE THREAD

**Issue by Exanthos** [molenzwiebel/Deceive#165] opened 2022-11-07 17:29 UTC
the game launches but then decieve error pops up and decieve doesn't appear in-game

**Comment by Exanthos** [comment] 2022-11-07 17:32
![unknown_2022 11 07-19 31](https://user-images.githubusercontent.com/117673717/200376530-1e0f2d6f-2e1f-41d6-b92a-e9a84452c9f9.png)

**Comment by molenzwiebel** [comment] 2022-11-10 15:12
Duplicate of #164.

**Closed by molenzwiebel** 2022-11-10 15:12 UTC
